repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: ["--fix"]
        exclude: ^agent/|^manual_agent_test.py
      - id: ruff-format
        exclude: ^agent/|^manual_agent_test.py

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
        exclude: ^agent/|^manual_agent_test.py

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ^agent/|^manual_agent_test.py
      - id: end-of-file-fixer
        exclude: ^agent/|^manual_agent_test.py
      - id: check-yaml
        exclude: ^agent/|^manual_agent_test.py
      - id: check-added-large-files
        exclude: ^agent/|^manual_agent_test.py
